### ISSUE TITLE
assets/js folder is missing under the dist folder

### ISSUE THREAD

**Issue by Levent0z** [webdevnerdstuff/amazon-smile-redirect#101]
manifest.json references them but the minified JS files are not there.

**Comment by webdevnerdstuff** [comment]
That `dist` directory is more for when I'm packaging the extension into zip files for submitting them to the browsers. So the missing files are generated during the `grunt build` process. I added them in the .gitignore as there's no real need to have  those files committed to the repo as they just take up unnecessary space. It's not the best setup, but it serves it's purpose.

I have an update coming soon where I'm cleaning things up and changing build tools that better serve my needs. So that dist directory won't even be there anymore as it's not needed. The important readable code is in the main `src` directory.
