### ISSUE TITLE
Option: Display warning when trying to order through non-smile website

### ISSUE THREAD

**Issue by JKamsker** [webdevnerdstuff/amazon-smile-redirect#109]
**Describe the bug**
Sometimes the plugin redirects me, when it shouldn't, which creates an infinite loop or a not-breakable loop (prime video or drive).
Therefor i would like the idea more, where the plugin just warns me that im about to order through the non-smile portal. (Detectable through `/gp/cart/view.html` and `/gp/buy/itemselect/handlers/display.html`)

**Comment by webdevnerdstuff** [comment]
I am going to add `https://www.amazon.com/clouddrive` to the excluded redirect list. I was able to test that link and even when logged in it sent me to the login screen before going to smile, which is incorrect. That fix should go out in the extensions version 3.0.3.

As for Prime Video I was unable to replicate the issue there. As for the non-smile portal from the two paths you provided, I'm not sure I fully understand the issue, as those links work as intended for me. Could you provide me with a little more details?

Also which browser are you using, and extension version? 

There is a bug with version 3.0.1, the fix for that bug is in version 3.0.3. Which was causing the site to redirect even when the setting was set to off, but I don't think that's related to the issue you are having.

**Comment by JKamsker** [comment]
Hmm this primevideo thing happened to me before the new version of pv... Maybe this got implicitly fixed 😅

Thx for the cd fix.

Ill open a new issue when new problems occur

**Comment by webdevnerdstuff** [comment]
No problem.
