### ISSUE TITLE
Smile redirect messes up amazon pay

### ISSUE THREAD

**Issue by JKamsker** [webdevnerdstuff/amazon-smile-redirect#113]
**Describe the bug**
The login popup never goes away when using amazon pay on external shops. Works with plugin disabled.

**To Reproduce**
- Put smth in your cart: https://www.worldofsweets.de/index.php?cl=user
- Select amazon pay for payment
- Be sure you are logged out from amazon
- The login popup never goes away

**Expected behavior**
The login process actually complete

**Desktop (please complete the following information):**
 - OS: Windows
 - Firefox Version 108.0.1
 - Extension Version 3.0.4

**Comment by webdevnerdstuff** [comment]
I was able to replicate the issue. I'm not sure if I can figure out a way to fix this one. Let me try to explain, and do a little thinking out loud in the hopes it gives me or someone else an idea on how to fix this.

The problem is that `payments.amazon` is in the excluded sites list, but after submitting the email, the url changes to a basic login form `https://www.amazon.de/ap/signin` via a post call.

The first URL goes to something like this
`https://www.amazon.de/ap/signin?openid.return_to=https%3A%2F%2Fpayments.amazon.de...`

Then Amazon makes a post request and redirects to this url `https://www.amazon.de/ap/signin` to enter the password. The problem with this is that I think it's using session data, and when the url changes there's nothing for the extension to detect if it should not redirect. You can't even go to that URL without first having entered the email/username step first. Or at least I think that's the issue.

The only way around this currently, is to turn on the option "Redirect only when logged in" or "Redirect only when logged in". It seemed to work ok with one of those settings on. I will try to keep on thinking if there's a way to fix it, but currently I'm not sure of a way.
