### ISSUE TITLE
Adding a privacy policy for the extension

### ISSUE THREAD

**Issue by momenabdelkarim** [webdevnerdstuff/amazon-smile-redirect#36]
(Skipping the template since it doesn't apply to my issue)

Would it be possible to add a brief Privacy Policy in the README? I read through the code to confirm the extension _just redirects_ to Amazon Smile and nothing more. I didn't see any data collection/usage/nefarious activities occurring, but it would be nice to have official confirmation to reassure myself and other users.

In the meantime, could you confirm my findings (that there is no data being collected and nothing occurring beyond just redirecting to Amazon.com to Amazon Smile)?

Thanks for creating this extension!

**Comment by webdevnerdstuff** [comment]
Zero user data is being collected from this extension. 

I actually am working on the webpage for the extension that does have a privacy policy. Unfortunately that's been delayed due to the current situation in the world going on, and my graphic designer has been swamped with other work. Hopefully I'll have that up eventually.

I'll add a little blurb to the README though as it's a good idea to have something here as well. 

Thanks for the feedback!

**Comment by webdevnerdstuff** [comment]
Finally got around to adding it into the readme.
