### ISSUE TITLE
[Feature Request] Turn off redirect for select websites

### ISSUE THREAD

**Issue by dvoraking** [webdevnerdstuff/amazon-smile-redirect#47]
Hi. Not sure if you'd prefer these requests on Github or the Chrome web store. I prefer here for anonymity. Can you provide the option to turn off certain country smile domains, like US and DE? Just so I can check those links without having to log into Amazon?

**Comment by webdevnerdstuff** [comment]
When you want to visit those pages without logging in, you can just disable the extension in it's menu. That will prevent it from redirecting you. Then when you are done you can just enable it again. The next time I do any upgrades or bug fixes I will take a look to see if it's feasible to have it enable/disable specific Smile sites without the need to make major changes.

The reason it wants you to login to Amazon first is because if it doesn't, some pages cause a redirect loop when not logged in. That is why my extension isn't as "fast" as others that do something similar. By checking to make sure you are logged in first, it prevent this redirect loop from happening.
