### ISSUE TITLE
Safari 14 support?

### ISSUE THREAD

**Issue by momenabdelkarim** [webdevnerdstuff/amazon-smile-redirect#52]
With the new WebExtensions support on Safari 14, I was wondering if this extension will support Safari 14?

**Comment by webdevnerdstuff** [comment]
I did want to make it for Safari, but unfortunately Apple requires you to be in their Apple Developer Program in order to list it in their web store, which comes with an annual fee of $99. Because of this I decided to not build it for Safari. I do not make money off this extension and rarely get donations for it, but maybe something like $5-$10 a year (if I'm lucky). With that, it's not really worth the time and effort and the amount of money it would cost me over time.

I looked into the WebExtensions support a little bit, and it still seems to be a bit lacking compared to other browsers, and still requires you to be in the Apple Developer Program. Unless I'm missing something, as I didn't go too deep into researching it.

**Comment by iMonZ** [comment]
> I did want to make it for Safari, but unfortunately Apple requires you to be in their Apple Developer Program in order to list it in their web store, which comes with an annual fee of $99. Because of this I decided to not build it for Safari. I do not make money off this extension and rarely get donations for it, but maybe something like $5-$10 a year (if I'm lucky). With that, it's not really worth the time and effort and the amount of money it would cost me over time.
> 
> I looked into the WebExtensions support a little bit, and it still seems to be a bit lacking compared to other browsers, and still requires you to be in the Apple Developer Program. Unless I'm missing something, as I didn't go too deep into researching it.

No need to be in the AppStore.
Their is a script that compiles the app for Safari on the PC without the need of a License or signing

**Comment by webdevnerdstuff** [comment]
@iMonZ it's still a bit of a pain in the butt to even load an unpackaged extension, and for a regular user with no tech knowledge, there is no way they are ever going to figure it out. Overall the juice isn't worth the squeeze to make it work in Safari, especially when there are much better browsers out there.
