### ISSUE TITLE
Add build documentation

### ISSUE THREAD

**Issue by melizeche** [webdevnerdstuff/amazon-smile-redirect#58]
I'll love to contribute with this project but I'm a little lost with how to build locally for Firefox and Chrome, is this the right channel for asking for this?
Thanks

**Comment by webdevnerdstuff** [comment]
I'm not currently looking for contributors at this time, but thank you.

But if you really want to try it out locally, here are some links to start you off with. I apologize if you already know this information, I just have to assume since I do not know your level of experience.

- [Fork a Repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo)
- [Chrome Extensions](https://developer.chrome.com/docs/extensions)
- [Firefox Extensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions)
- [Grunt](https://gruntjs.com/)
