### ISSUE TITLE
Forced Sign-In

### ISSUE THREAD

**Issue by OPStellar** [webdevnerdstuff/amazon-smile-redirect#69]
**Describe the bug**
Whenever it triggers, it forces me to sign in (to smile.amazon.*) before proceeding.

**To Reproduce**
This may have something to with interference from other extensions that are designed to interact with Amazon.

**Expected behavior**
What should happen instead is that the site will be reloaded but with 'smile' in place of 'www', right?

**Desktop (please complete the following information):**
 - OS: Mac
 - [Opera GX](https://opr.as/91n2) (Chromium-based browser, capable of running any and all Chrome Extensions)

**Additional context**
If I click on a link from an email and it takes me to [www.amazon.com/*], Amazon Smile Redirect forces it before the page can fully load so that I cannot return to the page except by logging in.

**Comment by webdevnerdstuff** [comment]
In order to shop on AmazonSmile, a user must be logged into their amazon account.  So even if you have the extension turned off, or if you don't have any extensions installed, AmazonSmile will redirect you back to amazon.com as part of their webpage. This is completely independent of any extensions and purposely done by Amazon.

Most other extensions similar to mine, do not check for this, which causes a redirect loop to occur. So for other extensions if you got to amazon.com, it redirects you to smile.amazon.com, and then Amazon redirects you back to amazon.com, then the extension sends you back to smile.amazon.com, and Amazon again sends you back to amazon.com... and so on, and this process will keep repeating itself.

My extension is one of, if not the only one of this kind that checks to make sure that the user is logged in before going to smile.amazon.com, which in turn prevents a redirect loop to occur. Also with this extension, if you click on a link, and it takes you to amazon.com, the extension will send you to the AmazonSmile login, and once you login, it will continue to the original link you clicked on, but on smile.amazon.com. So if you are going to a products page, after the login, it will still go the the products page (as long as it's also on AmazonSmile, as not all products are it seems).
