### ISSUE TITLE
Prevent redirect on amazon.com/ask/*

### ISSUE THREAD

**Issue by craigsnyders** [webdevnerdstuff/amazon-smile-redirect#75]
This url creates an infinite redirect loop: https://www.amazon.com/ask/questions/TxQL182S66601T

**Comment by webdevnerdstuff** [comment]
I need more information before I can look into this.

Please use this as a template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Windows]
 - Chrome Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
