### ISSUE TITLE
Redirects to Smile for amazon.de even when not logged in

### ISSUE THREAD

**Issue by PhoenixIV** [webdevnerdstuff/amazon-smile-redirect#80]
With this plugin I get redirected to Amazon Smile for .de even if I am not logged in.

**Screenshots**
https://youtu.be/yehLPsq5ZlQ

**Additional context**
Thank you for inviting me to report this bug over in the Firefox addons comment section.

I found no reason for this issue in your code.
Here are the first three `nav-line-1` classes in order:

```
                <span class="nav-line-1 nav-progressive-content" id="glow-ingress-line1">
                   Hallo
                </span>

      <span class="nav-line-1">
      </span>

<span id="nav-link-accountList-nav-line-1" class="nav-line-1 nav-progressive-content">Hallo, Anmelden</span>
```

I do not understand why you do not use `span id="nav-link-accountList-nav-line-1"`

Consider https://github.com/Aaron-P/SmartAmazonSmile, it uses **Cookies** to determine a session and it therefore reacts instantly before site content is even loaded.

And thanks for your work.

**Desktop (please complete the following information):**
Firefox 94.0.2 (64-Bit)
Extension Version 2.1.2

**Comment by webdevnerdstuff** [comment]
Thank you for coming over here to give some more information. It is actually very helpful.

The plugin is supposed to go to the login page if you are not logged in. You have to be logged in before you can load the AmazonSmile page, or it will redirect you back to the regular site. Which would cause an endless redirect loop. So that functionality is working as it should. To stop it a user can just turn off the extension via the Extension icon menu.

What I find **very** useful though is how the other Extension uses Cookies to determine the session. I looked into checking cookies years ago, but wasn't sure what Amazon was setting, and since the Extension worked I kind of forgot about it. Using cookies might be something to deter users from installing the extension, and it might require updating the extension permissions. To be honest, I'm not positive off the top of my head, so I'll have to look into that more. I've never really liked how I checked if the user was logged in, so I do find this approach interesting.

When I have some more time I'll definitely be looking into this more as it's something I have wanted in the past. So thank you for sharing that other Extension. I'd have to figure out my own way of doing it as I don't want to just copy code from another developer.

I would ask you reconsider the rating you gave the Extension, as it is actually working as intended.

**Comment by PhoenixIV** [comment]
I much prefer the behaviour of "Smart Amazon Smile". "Amazon Smile Redirect" forces me to log in to Amazon, which is completely unnecessary and privacy-unfriendly. I only ever need Smile when I want to click "order now", and that I only do after logging in.

**Comment by webdevnerdstuff** [comment]
If you prefer the other extension over this one, that is fine, I have no problem with that. Not everybody wants the same exact user experience. So if you prefer that one, then it is a better fit for you. No extension can consider every single use case for every single user, so I have to go with what is most effective for most users.

Sending the user to the login page is not privacy unfriendly, as this extension does not collect any user data, and does not track user activity at all. Browsers require you to state what permissions and explain the reasoning for it before they will even publish it. Chrome specifically is very strict when it comes to this.

> What does "This extension considers if you are logged in" mean?
That just means it checks to see if the page has the "Hello" {Users name} on the page to see if the user is logged in. If it finds that text, it proceeds to send the user to the corresponding AmazonSmile page. If it does not, it send the user to the login page so the user can login, and the continues onto the page they were originally trying to load. It does not look at cookies as well (Smart Amazon Smile does), which can be a privacy issue. That is why [GDPR](https://gdpr-info.eu/) is a big thing. I have my code available for anybody to look at to make sure there is 100% transparency that my code is secure and does not have any privacy issues.

> If it is supposed to always go to the login page, then there is no need to write code for it, as just redirecting any site to smile will automatically trigger a log in by amazon if necessary.
That is incorrect, if you are not logged into Amazon and go to an AmazonSmile link (other than the homepage), it sends you back to the regular site. It does not send you to the login page. Many people will not notice this and proceed with their purchase and their non-profit will get nothing from the transaction.

That is why the Extension considers if you are logged in or not. If you are not logged in, it sends you to the login page, then onto AmazonSmile. If you are logged in, then it just sends you to AmazonSmile and that page will load as it should without sending you back to Amazon. The entire purpose of the extension is to "redirect" you to AmazonSmile, not "only if you are logged in".

Please do not just give me a negative review for the extension doing exactly as advertised and what it's supposed to do, just because you prefer how another extension works. By all means give the other extension a good rating if you like theirs. I'm sure the developer will appreciate it. 

I made this extension to help non-profits, so it does bother me when people give me a negative review for the extension working as intended to make sure non-profits make as much money as possible. I have been offered thousands of dollars for my extension multiple times, but I refuse to sell it which could cause users to be exploited for data mining. I have spent many years developing this extension to what it is today, and it's 100% to help non-profits.

**Comment by PhoenixIV** [comment]
I took some time to understand why you state the plugin works as intended. I understand it a little better now. Thank you, I was not aware you could not just refer every request to smile.

I just see no reason to force users to log in. If log in is only necessary to purchase and not to browse the site, what is the advantage of always being logged in?
It is privacy-unfriendly because this way, if I would log in, Amazon is able to track all my movements.

And please don't try to shame me into changing my opinion. Helping people to use smile is wonderful work. Greenwashing no matter what.

**Comment by webdevnerdstuff** [comment]
Next release I plan on adding a new setting for the user to choose if the extension should redirect when logged off or only when logged in.

**Comment by webdevnerdstuff** [comment]
@PhoenixIV I opened a discussion for adding this as a new feature. I'd like to get your thoughts about it if you have any specific ideas about it. 

https://github.com/webdevnerdstuff/amazon-smile-redirect/discussions/81

**Comment by webdevnerdstuff** [comment]
@PhoenixIV I think I might almost be done adding this new feature. I still need to do some more QA testing, as well as update all the translation files before it can be published. Let me know what you think. I'm still not 100% on the verbiage for the setting. Feedback would be appreciated in the discussion page.

https://github.com/webdevnerdstuff/amazon-smile-redirect/tree/discussion-81

**Comment by webdevnerdstuff** [comment]
I just released version 2.2.0, which now has the ability to set an option to only redirect when logged in.

I hope you will now reconsider your rating @PhoenixIV ;)

**Comment by webdevnerdstuff** [comment]
Reopening the issue as the published version doesn't seem to be working correctly. Working on fixing it now.

**Comment by webdevnerdstuff** [comment]
My bad, I was logged in already thinking I wan'

**Comment by PhoenixIV** [comment]
Oh boy. I have not even tested this out but I am sure this deserves deleting my rating 😀

**Comment by webdevnerdstuff** [comment]
Thank you. Hopefully this new feature is what you were looking for, and others will find it useful as well. :)
