### ISSUE TITLE
Redirect issue when resetting password

### ISSUE THREAD

**Issue by billyschmidt** [webdevnerdstuff/amazon-smile-redirect#98]
**Describe the bug**
When following the email link for a password reset, you are immediately redirected and can't click the "Allow Access" button

**To Reproduce**
1. reset amazon password
2. follow the link
3. see unexpected redirect

**Expected behavior**
Don't redirect on password reset links

**Screenshots**

**Desktop (please complete the following information):**
- most recent everything

**Additional context**

**Comment by IdiosApps** [comment]
Suggestion: Should redirect to https://smile.amazon... only happen when users go to the basket/checkout?

Pros:
- Users get their usual Amazon experience until they go to basket/checkout
    - This should help with redirect bugs on other pages, like for this ticket 

- Only redirect when necessary / actually useful 
    - I might open a tab and go to Amazon 10 times, but only go to checkout once. Those 9 redirects don't give anything to charity, they just make the browsing experience a little bit worse

Cons:
- Question: would Amazon smile still work if users only switch to the smile website at checkout?

**Comment by webdevnerdstuff** [comment]
@billyschmidt I was on holiday last month, thus the delay in my response. I'll take a look at this as soon as I get settled back in. It might just be as easy as adding some more pages to the list of excluded pages to redirect. I'm in the middle of actually doing some rebuilding of the extension to reduce overhead, and clean some things up, as well as updated it for Manifest version 3. So the fix will most likely be when that is ready to release.

**Comment by webdevnerdstuff** [comment]
@IdiosApps I have thought of that before, but ultimately I think people like to know they are on AmazonSmile the entire time, not just when they go to checkout. 

I get what you are saying when it comes to opening a bunch of Amazon tabs. I often find myself opening a bunch of Amazon pages from a review site and all of them redirecting. 

Since you bring this up, perhaps an idea would be to add another setting for users to be able to choose to only redirect on checkout, instead of in general. This way it would satisfy multiple users/situations. If you think this sounds like a good idea and have more specific details and ideas, please add a post to the [Discussions](https://github.com/webdevnerdstuff/amazon-smile-redirect/discussions) page so I can keep track of that separately from this Issue. As I mentioned in my previous post, I'm doing some rebuilding the extension, so if this get's added it would be when it's ready to release.

As for your question if AmazonSmile still works if users only switch at checkout, the answer is yes. As long as you finish the purchase and checkout on AmazonSmile, your charity should get their percentage.

**Comment by IdiosApps** [comment]
Thanks @webdevnerdstuff ! I have opened https://github.com/webdevnerdstuff/amazon-smile-redirect/discussions/100 :)

**Comment by webdevnerdstuff** [comment]
@billyschmidt How do you get it to send you an email to reset your password? I have tried the "forgot your password" when logged out link, but that just sends me a "One Time Password (OTP)" to use, not a link to reset the password.
